cmake_minimum_required(VERSION 3.23)
project(ir-facts LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
find_package(LLVM REQUIRED CONFIG)
list(APPEND CMAKE_MODULE_PATH "${LLVM_CMAKE_DIR}")
include(AddLLVM)
add_definitions(${LLVM_DEFINITIONS})
include_directories(SYSTEM ${LLVM_INCLUDE_DIRS})
if(NOT LLVM_ENABLE_RTTI)
  add_compile_options("-fno-rtti")
endif()
llvm_map_components_to_libnames(llvm_libs core support irreader bitreader demangle)
add_executable(ir-facts ir-facts.cpp)
target_link_libraries(ir-facts PRIVATE ${llvm_libs})
