#!/usr/bin/env python3
"""Generate the one-node-per-job pipeline diagram: docs/design-parity/pipeline-job-graph.mermaid.

`job-graph.mmd` (phase1.py graph) draws every job as four step nodes, which is exact but unreadable at
71 jobs. This view draws one node per lifecycle job, grouped by lane in `process-manifest.json` order,
with the same dependency edges. 03-threat-model-dfd-stride is drawn as a subgraph holding its threat
workbench cells (ADR-0019), read from `threat_workbench.WORKCELLS` / `NOT_BUILT` without importing it.

Sources:
  appsec-review-process/job-graph.json          nodes, lanes, dependencies (required / optional / disabled)
  appsec-review-process/process-manifest.json   lane order
  appsec-review-process/threat_workbench.py     workbench cells and waves

Usage:
  python3 docs/design-parity/pipeline_job_graph.py           # regenerate
  python3 docs/design-parity/pipeline_job_graph.py --check   # exit 1 if the diagram is stale

Standard library only.
"""
from __future__ import annotations

import argparse
import ast
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PROC = ROOT / 'appsec-review-process'
OUT = ROOT / 'docs' / 'design-parity' / 'pipeline-job-graph.mermaid'
WORKBENCH_JOB = '03-threat-model-dfd-stride'


def node_id(job: str) -> str:
    return 'j_' + job.replace('-', '_')


def workbench_cells() -> tuple[list[tuple[str, int, str]], list[tuple[str, int]]]:
    """(built cells as (id, wave, selection), not-built cells as (id, wave)) from threat_workbench.py."""
    tree = ast.parse((PROC / 'threat_workbench.py').read_text(encoding='utf-8'))
    built, not_built = [], []
    for node in tree.body:
        if not (isinstance(node, ast.Assign) and len(node.targets) == 1 and isinstance(node.targets[0], ast.Name)):
            continue
        name = node.targets[0].id
        if name == 'WORKCELLS':
            for call in node.value.elts:
                args = [ast.literal_eval(a) for a in call.args[:4]]
                built.append((args[0], args[1], args[3]))
        elif name == 'NOT_BUILT':
            for row in ast.literal_eval(node.value):
                not_built.append((row[0], row[1]))
    if not built:
        raise SystemExit('threat_workbench.py: WORKCELLS not found')
    return built, not_built


def render() -> str:
    jobs = json.loads((PROC / 'job-graph.json').read_text(encoding='utf-8'))['jobs']
    order = json.loads((PROC / 'process-manifest.json').read_text(encoding='utf-8'))['process_order']
    rank = {lane: i for i, lane in enumerate(order)}
    lanes: dict[str, list[str]] = {}
    for job, spec in jobs.items():
        lanes.setdefault(spec['lane'], []).append(job)
    built, not_built = workbench_cells()

    out = [
        '%% Generated by python3 docs/design-parity/pipeline_job_graph.py; do not edit by hand.',
        f'%% {len(jobs)} lifecycle jobs from appsec-review-process/job-graph.json, one node each, grouped by lane.',
        '%% Solid: required input. Dashed: optional input. Dotted "off": optional input disabled by default.',
        '%% 03-threat-model-dfd-stride is drawn with its threat workbench cells (ADR-0019); the step-level',
        '%% graph is job-graph.mmd.',
        'flowchart LR',
        '  classDef notbuilt fill:#f6f6f6,stroke:#999,color:#666,stroke-dasharray:4 3',
        '  classDef cell fill:#eef4ff,stroke:#245a9b,color:#102a43',
    ]
    for lane in sorted(lanes, key=lambda l: (rank.get(l, 999), l)):
        out.append(f'  subgraph lane_{lane.replace("-", "_")}["{lane}"]')
        for job in lanes[lane]:
            if job == WORKBENCH_JOB:
                nid = node_id(job)
                out.append(f'    subgraph {nid}["{job} (threat workbench)"]')
                out.append(f'      {nid}_core["deterministic DFD/STRIDE core"]')
                for wave in sorted({w for _, w, _ in built} | {w for _, w in not_built}):
                    for cell, w, selection in built:
                        if w == wave:
                            label = cell if selection == 'always' else f'{cell}<br/>({selection})'
                            out.append(f'      {nid}_{cell.replace("-", "_")}["wave {w}: {label}"]:::cell')
                    for cell, w in not_built:
                        if w == wave:
                            out.append(f'      {nid}_{cell.replace("-", "_")}["wave {w}: {cell}<br/>(not built)"]:::notbuilt')
                out.append(f'      {nid}_join["join + overlay validator"]')
                for cell, w, _ in built:
                    src = f'{nid}_core' if w == 1 else f'{nid}_wave1'
                    out.append(f'      {src} --> {nid}_{cell.replace("-", "_")} --> {nid}_join')
                out.append(f'      {nid}_core --> {nid}_join')
                out.append('    end')
            else:
                out.append(f'    {node_id(job)}["{job}"]')
        out.append('  end')
    # Wave-2 cells read wave 1's model; draw that as one hand-off node inside the workbench subgraph.
    nid = node_id(WORKBENCH_JOB)
    out.insert(out.index(f'      {nid}_join["join + overlay validator"]'),
               f'      {nid}_wave1(["wave-1-model.json"])')
    for cell, w, _ in built:
        if w == 1:
            out.append(f'  {nid}_{cell.replace("-", "_")} --> {nid}_wave1')
    for job, spec in jobs.items():
        for dep in spec['dependencies']:
            src, dst = node_id(dep['job']), node_id(job)
            if dep['kind'] == 'required':
                out.append(f'  {src} --> {dst}')
            elif dep.get('enabled', True):
                out.append(f'  {src} -.->|optional| {dst}')
            else:
                out.append(f'  {src} -.->|off| {dst}')
    return '\n'.join(out) + '\n'


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--check', action='store_true', help='exit 1 if the diagram is stale')
    args = parser.parse_args()
    text = render()
    if args.check:
        if not OUT.exists() or OUT.read_text(encoding='utf-8') != text:
            print(f'{OUT.relative_to(ROOT)} is stale: run python3 docs/design-parity/pipeline_job_graph.py',
                  file=sys.stderr)
            return 1
        print('pipeline job graph: ok')
        return 0
    OUT.write_text(text, encoding='utf-8')
    print(f'wrote {OUT.relative_to(ROOT)}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
