ARG CODEQL_SOURCE_IMAGE
FROM ${CODEQL_SOURCE_IMAGE}
ARG RUNTIME_USER=10001:10001
USER 0:0
COPY codeql_runner.py /opt/appsec/codeql_runner.py
RUN chmod 0555 /opt/appsec/codeql_runner.py
ENV PATH=/opt/codeql:${PATH}
USER ${RUNTIME_USER}
WORKDIR /scratch
