"""02-evidence-index-derived: Python selection, derived records, build inputs, text, query and the menu."""
import json
import sys
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(Path(__file__).resolve().parent))

import evidence_index_derived as derived
import evidence_index_enrichment as enrichment
import execution_state as state
import input_mcp
import supporting_evidence_menu as menu_module
from execution_state import atomic_json, file_hash, tree_hashes
from publish_job_output import ACCEPTED_SCHEMA
from schema_validate import validate_document
from test_evidence_index_enrichment import ATTEMPT, JOB as DOC_JOB, RUN_ID, SOURCE, ProducerFixture
from worker_result import artifact_records, terminal_envelope

DEPENDENCIES = {
    "schema": "appsec-review/build-dependencies/1", "distro": None, "package_manager": "dpkg",
    "limits": {"files": 8192, "translation_units": 8192, "link_commands": 1024, "edges": 1 << 20,
               "hash_max_bytes": 256 << 20, "seconds": 1800},
    "search_dirs": {"include": ["/usr/include", "lib"], "library": ["/usr/lib/x86_64-linux-gnu"]},
    "files": [
        {"path": "/usr/include/openssl/ssl.h", "class": "system-package", "kinds": ["header"],
         "sha256": "sha256:" + "1" * 64, "size_bytes": 10, "packages": ["libssl-dev:amd64"]},
        {"path": "/usr/lib/x86_64-linux-gnu/libssl.so.3", "class": "system-package", "kinds": ["needed"],
         "sha256": "sha256:" + "2" * 64, "size_bytes": 20, "packages": ["libssl3:amd64"]}],
    "packages": [{"package": "libssl-dev:amd64", "name": "libssl-dev", "arch": "amd64", "version": "3.0.11-1",
                  "source": "openssl", "source_version": "3.0.11-1"}],
    "translation_units": [], "link_commands": [],
    "binaries": [{"path": "src/hello", "needed": [{"soname": "libssl.so.3", "file": 1, "via": "cache"}],
                  "runpath": [], "rpath": []}],
    "omitted": {"files": 0, "translation_units": 0, "link_commands": 0, "edges": 0, "hashes": 0},
    "coverage_gaps": []}
HEADER = b"/* generated by configure */\n#define HAVE_GENERATED_MARKER 1\n#define PACKAGE_NAME \"hello\"\n"


def accept(base: Path, run: str, job: str, attempt: Path, status: str = "OK", extra: dict | None = None) -> None:
    atomic_json(base / "latest.json", {"attempt_id": attempt.name})
    atomic_json(base / "accepted.json", {"schema": ACCEPTED_SCHEMA, "status": status, "run_id": run, "job": job,
        "attempt_id": attempt.name, "fingerprint": "sha256:" + "e" * 64, "envelope_path": "result.json",
        "envelope_sha256": file_hash(attempt / "result.json"), "hashes": tree_hashes(attempt),
        "accepted_at": "2026-01-01T00:00:02+00:00", **(extra or {})})


def plain_envelope(attempt: Path, paths: list[str]) -> None:
    atomic_json(attempt / "result.json", {"artifacts": [
        {"path": path, "sha256": file_hash(attempt / path), "media_type": "application/octet-stream"} for path in paths]})


class DerivedIndexTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.old_runs = state.RUNS
        state.RUNS = Path(self.temp.name)
        self.jobs = state.RUNS / RUN_ID / "data" / "jobs"
        self.doc = ProducerFixture(state.RUNS)
        index = self.jobs / "02-evidence-index" / "whole"
        attempt = index / "attempts" / "index-1"
        atomic_json(attempt / "lineage.json", {"source_snapshot_sha256": "sha256:" + SOURCE})
        plain_envelope(attempt, ["lineage.json"])
        accept(index, RUN_ID, "02-evidence-index", attempt)

    def tearDown(self):
        state.RUNS = self.old_runs
        self.temp.cleanup()

    def native_build(self):
        base = self.jobs / "02-native-build"
        attempt = base / "attempts" / "build-1"
        atomic_json(attempt / "outputs/u1/build-dependencies.json", DEPENDENCIES)
        header = attempt / "outputs/u1/generated-headers/config.h"
        header.parent.mkdir(parents=True)
        header.write_bytes(HEADER)
        dependencies = attempt / "outputs/u1/build-dependencies.json"
        atomic_json(attempt / "native-build.json", {"units": [{"unit_id": "u1",
            "build_dependencies": {"path": "outputs/u1/build-dependencies.json", "sha256": "sha256:" + file_hash(dependencies)},
            "generated_headers": {"root": "outputs/u1/generated-headers", "omitted": 0,
                "headers": [{"path": "config.h", "sha256": "sha256:" + file_hash(header), "size_bytes": len(HEADER)}]}}]})
        plain_envelope(attempt, ["native-build.json", "outputs/u1/build-dependencies.json",
                                 "outputs/u1/generated-headers/config.h"])
        accept(base, RUN_ID, "02-native-build", attempt)
        return attempt

    def run_job(self):
        return derived.run(RUN_ID, "dagster-test")

    def result(self):
        pointer = json.loads((derived.root(RUN_ID) / "accepted.json").read_text())
        return json.loads((derived.root(RUN_ID) / "attempts" / pointer["attempt_id"] / derived.RESULT).read_text())

    def test_selection_is_computed_from_the_producers_present(self):
        skipped = self.jobs / "02-codeql-ruby"
        atomic_json(skipped / "accepted.json", {"status": "SKIPPED", "reason": "not-applicable-language-absent"})
        inputs = derived.current_inputs(RUN_ID)
        self.assertEqual([item["job_id"] for item in inputs["included"]], [DOC_JOB])
        excluded = {item["job_id"]: item["disposition"] for item in inputs["excluded"]}
        self.assertEqual(set(excluded) | {DOC_JOB}, set(enrichment.PROFILES) | set(enrichment.NOT_INDEXABLE))
        self.assertEqual(excluded["02-code-property-graph"], "absent")
        self.assertEqual(excluded["02-codeql-ruby"], "skipped")
        self.assertEqual(excluded["01-component-characterization"], "not-selectable")
        self.assertEqual(excluded["02-sbom-inventory"], "not-indexable")

    def test_absent_producer_is_a_gap_and_index_is_nonempty(self):
        self.run_job()
        result = self.result()
        self.assertEqual(validate_document(result, derived.SCHEMA_FILE), [])
        self.assertEqual(result["status"], "OK_WITH_GAPS")
        self.assertTrue(any(gap.startswith("producer-absent:02-code-property-graph:") for gap in result["coverage_gaps"]))
        self.assertTrue(any(gap.startswith("build-inputs-absent:02-native-build") for gap in result["coverage_gaps"]))
        self.assertGreater(result["enrichment"]["record_count"], 0)
        self.assertEqual(result["selection"]["included"][0]["job_id"], DOC_JOB)
        derived.validate(RUN_ID)

    def test_evidence_derived_returns_hits_only_after_acceptance(self):
        before = input_mcp.call(RUN_ID, None, "evidence_derived", {"text": "reporting"})
        self.assertEqual(before["results"], [])
        self.assertTrue(before["coverage_gaps"][0].startswith("derived-index-absent:"))
        self.run_job()
        after = input_mcp.call(RUN_ID, None, "evidence_derived", {"text": "reporting", "limit": 5})
        self.assertTrue(after["results"])
        self.assertEqual(after["results"][0]["producer_job_id"], DOC_JOB)
        self.assertTrue(after["coverage_gaps"])

    def test_build_inputs_records_and_generated_headers_are_searchable(self):
        self.native_build()
        self.run_job()
        result = self.result()
        unit = result["build_inputs"]["units"][0]
        self.assertEqual((unit["generated_headers"], unit["out_of_checkout_headers"]), (1, 1))
        self.assertTrue(any(gap.startswith("out-of-checkout-headers-not-retained:u1:1") for gap in result["coverage_gaps"]))
        hits = derived.query(RUN_ID, text="libssl-dev")
        labels = {item["type_label"] for item in hits["results"]}
        self.assertIn("build-dependencies:files", labels)
        self.assertIn("build-dependencies:packages", labels)
        self.assertEqual(hits["results"][0]["producer_job_id"], "02-native-build")
        text = derived.query(RUN_ID, text="HAVE_GENERATED_MARKER")
        self.assertEqual(text["text_hits"][0]["artifact_path"], "outputs/u1/generated-headers/config.h")
        self.assertEqual(text["text_hits"][0]["start_line"], 1)
        derived.validate(RUN_ID)

    def test_overflow_and_non_utf8_are_gaps(self):
        attempt = self.native_build()
        with patch.dict(derived.LIMITS, {"build_records_max": 2, "text_max_files": 0}):
            self.run_job()
            result = self.result()
        self.assertTrue(any(gap.startswith("build-records-omitted:") for gap in result["coverage_gaps"]))
        self.assertTrue(any(gap.startswith("text-not-indexed:over-file-count:") for gap in result["coverage_gaps"]))
        self.assertEqual(result["text"]["files"][0]["status"], "over-file-count")
        corpus = derived._Text()
        bad = attempt / "bad.txt"
        bad.write_bytes(b"\xff\xfe broken")
        corpus.add(attempt, {"kind": "converted-document", "producer_job_id": "x", "producer_attempt_id": "a",
                             "artifact_path": "bad.txt", "sha256": "sha256:" + file_hash(bad), "source_path": "bad.doc",
                             "source_sha256": None, "converter": "fixture", "converter_version": "1"})
        self.assertEqual(corpus.files[0]["status"], "not-utf8")
        self.assertTrue(corpus.gaps[0].startswith("text-not-indexed:not-utf8:"))

    def test_producer_text_manifest_is_chunked_with_page_provenance(self):
        attempt = self.doc.attempt
        text = attempt / "text/design.txt"
        text.parent.mkdir()
        text.write_text("page one intro\nsecond line\npage two mentions TOKENROTATION policy\n", encoding="utf-8")
        atomic_json(attempt / derived.TEXT_MANIFEST, {"schema": "appsec-review/derived-text-manifest/1.0", "documents": [
            {"artifact_path": "text/design.txt", "sha256": "sha256:" + file_hash(text), "source_path": "docs/design.pdf",
             "source_sha256": None, "converter": "pdftotext", "converter_version": "24.02",
             "pages": [{"page": 1, "start_line": 1, "end_line": 2}, {"page": 2, "start_line": 3, "end_line": 3}]}]})
        envelope = terminal_envelope(run_id=RUN_ID, job_id=DOC_JOB, attempt_id=ATTEMPT, worker_kind="deterministic_python",
            execution_status="OK", acceptance_status="CURRENT", input_fingerprint="sha256:" + "f" * 64,
            output_contract="doc-intelligence", started_at="2026-01-01T00:00:00+00:00",
            finished_at="2026-01-01T00:00:01+00:00", summary="fixture", artifacts=artifact_records(attempt,
                ["doc-intelligence.json", "status.json", "permission.json", "lineage.json", derived.TEXT_MANIFEST,
                 "text/design.txt"]))
        atomic_json(attempt / "result.json", envelope)
        accept(self.doc.base, RUN_ID, DOC_JOB, attempt, extra={"fingerprint": "sha256:" + "f" * 64})
        self.run_job()
        self.assertEqual(self.result()["selection"]["included"][0]["job_id"], DOC_JOB)
        hit = derived.query(RUN_ID, text="TOKENROTATION")["text_hits"][0]
        self.assertEqual((hit["source_path"], hit["page"], hit["start_line"], hit["end_line"]), ("docs/design.pdf", 2, 3, 3))

    def test_menu_pins_build_dependencies_and_generated_headers(self):
        self.native_build()
        menu = menu_module.build(RUN_ID, "02-evidence-assembly", [], self.jobs)
        item = next(row for row in menu["items"] if row["item_id"] == "02-native-build")
        paths = {entry["path"].split("/accepted/")[1] for entry in item["files"] if entry["pinned"]}
        self.assertIn("outputs/u1/build-dependencies.json", paths)
        self.assertIn("outputs/u1/generated-headers/config.h", paths)


if __name__ == "__main__":
    unittest.main()
