"""02-language-census: one class per snapshot file, and what it changes downstream (tree-sitter no-grammar
paths and shebang grammars; 04-owasp-candidate-search completeness and coverage.file_classes)."""
from __future__ import annotations

import json
from pathlib import Path
import sys
import tempfile
import types
import unittest
from unittest.mock import patch

PROCESS = Path(__file__).resolve().parents[1]
ROOT = PROCESS.parent
sys.path.insert(0, str(PROCESS))

import execution_state as state  # noqa: E402
from execution_state import atomic_json, read_json  # noqa: E402
import language_census as census_mod  # noqa: E402
import owasp_candidate_search as search_mod  # noqa: E402
import owasp_universe as universe_mod  # noqa: E402
from schema_validate import validate_document  # noqa: E402
import treesitter_ast  # noqa: E402
import tests.test_adr34_owasp_participation as guard  # noqa: E402
from tests.test_owasp_candidate_search import RULES, document as search_document  # noqa: E402

CATALOG = read_json(PROCESS / census_mod.CATALOG_PATH)
HEX = "0" * 64
RUN_ID = "census-test"
SHELL = "#!/bin/sh\nfetch() {\n  curl -k https://example.invalid\n}\neval \"$1\"\n"
NON_PROGRAM = {"logo.png": b"\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR", "fix-build.patch": b"--- a/x\n+++ b/x\n@@ -1 +1 @@\n",
               "config.guess": b"#! /bin/sh\n# Attempt to guess a canonical system name.\necho x86_64-pc-linux-gnu\n",
               "README": b"hello: a small C program\n"}


def write(root: Path, files: dict[str, bytes | str]) -> Path:
    for path, data in files.items():
        target = root.joinpath(*path.split("/"))
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(data.encode("utf-8") if isinstance(data, str) else data)
    return root


def census(root: Path, **kwargs) -> dict:
    body = census_mod.census(root, RULES, CATALOG, **kwargs)
    return census_mod.document(body, run_id=RUN_ID, source_snapshot_sha256="sha256:" + HEX,
                               source_tree_sha256="sha256:" + HEX, rules_sha256=HEX)


class FakeNode:
    """A tree-sitter root with no children: enough for summarize_tree to walk."""
    is_error = is_missing = False
    is_named, type, children = True, "program", []

    def walk(self):
        node = self
        return types.SimpleNamespace(node=node, goto_first_child=lambda: False, goto_next_sibling=lambda: False,
                                     goto_parent=lambda: False)


class FakeParser:
    parsed: list[tuple[str, bytes]] = []

    def __init__(self, language):
        self.language = language

    def parse(self, data):
        FakeParser.parsed.append((self.language, data))
        return types.SimpleNamespace(root_node=FakeNode())


FAKE_TREE_SITTER = types.SimpleNamespace(Language=lambda value: value, Parser=FakeParser)


def scan(root: Path) -> treesitter_ast.Scan:
    FakeParser.parsed = []
    with patch.object(treesitter_ast, "load_languages",
                      return_value=({name: name for name in ("bash", "c", "python")}, {}, [])):
        result = treesitter_ast.Scan(root, tree_sitter=FAKE_TREE_SITTER, label="fixture")
        result.files = list(result.records())
    return result


class Classification(unittest.TestCase):
    def setUp(self):
        self.temporary = tempfile.TemporaryDirectory()
        self.addCleanup(self.temporary.cleanup)
        self.root = Path(self.temporary.name)

    def test_each_file_gets_one_class_by_path_name_suffix_shebang_then_sniff(self):
        write(self.root, {**NON_PROGRAM, "src/hello.c": "int main(void) { return 0; }\n", "Makefile.am": "bin_PROGRAMS = hello\n",
                          "configure": "#! /bin/sh\n# Generated by GNU Autoconf\n", "LICENSE.GPL": "GPL\n",
                          "doc/hello.1": ".TH HELLO 1\n", "lib/libx.so.1": b"\x7fELF\x02\x01", "blob.dat": b"ab\x00cd",
                          "run-tests": "#!/usr/bin/env python3\nprint(1)\n", "tool": "#!/usr/bin/tclsh\nputs x\n",
                          "debian/rules": "#!/usr/bin/make -f\n%:\n\tdh $@\n", "notes": "plain text\n",
                          "vendor/zlib/inflate.c": "int inflate;\n", "api/x.pb.go": "package api\n", "yarn.lock": "x\n",
                          "app/Main.kt": "fun main() {}\n", "settings.json": "{}\n"})
        result = census(self.root)
        self.assertEqual(validate_document(result, census_mod.SCHEMA_FILE), [])
        rows = {row["path"]: (row["class"], row["language"], row["basis"], row["interpreter"]) for row in result["files"]}
        self.assertEqual(rows, {
            "Makefile.am": ("build_system", None, "name", None),
            "LICENSE.GPL": ("documentation", None, "name", None),
            "README": ("documentation", None, "name", None),
            "api/x.pb.go": ("generated", None, "path", None),
            "app/Main.kt": ("program:kotlin", "kotlin", "suffix", None),
            "blob.dat": ("binary_media", None, "sniff", None),
            "config.guess": ("build_system", None, "name", None),
            "configure": ("generated", None, "name", None),
            "debian/rules": ("build_system", None, "shebang", "make"),
            "doc/hello.1": ("documentation", None, "suffix", None),
            "fix-build.patch": ("patch_diff", None, "suffix", None),
            "lib/libx.so.1": ("binary_media", None, "sniff", None),
            "logo.png": ("binary_media", None, "suffix", None),
            "notes": ("unknown_text", None, "sniff", None),
            "run-tests": ("program:python", "python", "shebang", "python"),
            "settings.json": ("data_config", None, "suffix", None),
            "src/hello.c": ("program:c", "c", "suffix", None),
            "tool": ("unknown_text", None, "shebang", "tclsh"),
            "vendor/zlib/inflate.c": ("vendored", None, "path", None),
            "yarn.lock": ("generated", None, "name", None)})
        self.assertEqual(result["languages"], [{"language": "c", "file_count": 1}, {"language": "kotlin", "file_count": 1},
                                               {"language": "python", "file_count": 1}])
        self.assertEqual([(row["language"], row["catalog_language"]) for row in result["languages_needing_server"]],
                         [("c", "cpp"), ("python", "python")])
        self.assertEqual(result["languages_needing_server"][0]["servers"], ["clangd"])
        unknown = [gap for gap in result["gaps"] if gap["kind"] == "unknown-text"]
        self.assertIn("notes, tool", unknown[0]["detail"])
        self.assertEqual(sum(row["file_count"] for row in result["classes"]), result["totals"]["files"])

    def test_a_nul_byte_is_binary_media_whatever_the_name(self):
        write(self.root, {"data": b"MAGIC\x00\x01", "font": b"wOFF....", "text": "ok\n"})
        rows = {row["path"]: row["class"] for row in census(self.root)["files"]}
        self.assertEqual(rows, {"data": "binary_media", "font": "binary_media", "text": "unknown_text"})
        self.assertEqual(census_mod.classify("x", b"a" * 9000 + b"\x00"), ("unknown_text", None, "sniff", None))

    def test_shebang_forms(self):
        cases = {b"#!/bin/sh\n": "bash", b"#! /bin/dash -e\n": "bash", b"#!/usr/bin/env zsh\n": "bash",
                 b"#!/usr/bin/env -S python3.12 -u\n": "python", b"#!/usr/bin/perl -w\n": "perl",
                 b"#!/usr/bin/env ruby\n": "ruby", b"#!/usr/local/bin/node\n": "javascript", b"#!/usr/bin/php\n": "php"}
        for head, language in cases.items():
            self.assertEqual(census_mod.classify("bin/tool", head)[:3], ("program:" + language, language, "shebang"), head)
        self.assertEqual(census_mod.classify("bin/tool.sh", b"#!/usr/bin/python3\n")[:3], ("program:bash", "bash", "suffix"))

    def test_census_is_deterministic_and_bounded(self):
        write(self.root, {f"src/f{n}.c": f"int f{n};\n" for n in range(5)} | {"z.png": b"\x89PNG"})
        first, second = census(self.root), census(self.root)
        self.assertEqual(json.dumps(first, sort_keys=True), json.dumps(second, sort_keys=True))
        self.assertEqual([row["path"] for row in first["files"]], sorted(row["path"] for row in first["files"]))
        bounded = census(self.root, max_rows=2)
        self.assertEqual(validate_document(bounded, census_mod.SCHEMA_FILE), [])
        self.assertEqual((bounded["totals"]["listed"], bounded["totals"]["unlisted"]), (2, 4))
        self.assertEqual({row["class"]: row["file_count"] for row in bounded["classes"]},
                         {"program:c": 5, "binary_media": 1})
        self.assertEqual([gap["kind"] for gap in bounded["gaps"]], ["rows-overflow"])
        self.assertNotEqual(bounded["content_sha256"], first["content_sha256"])

    def test_cli_census_of_a_directory(self):
        write(self.root / "src", {"a.c": "int a;\n"})
        out = self.root / "census.json"
        self.assertEqual(census_mod.main(["--root", str(self.root / "src"), "--out", str(out)]), 0)
        value = json.loads(out.read_text())
        self.assertEqual(value["files"][0]["class"], "program:c")
        self.assertEqual(value["content_sha256"], census_mod.content_sha256({key: value[key] for key in census_mod.BODY}))


class TreeSitterPathsAndShebang(unittest.TestCase):
    def setUp(self):
        self.temporary = tempfile.TemporaryDirectory()
        self.addCleanup(self.temporary.cleanup)
        self.root = Path(self.temporary.name)

    def test_suffixless_shell_script_is_parsed_as_bash_and_no_grammar_files_are_listed_by_path(self):
        write(self.root, {"src/hello.c": "int main(void) { return 0; }\n", "fetch": SHELL, **NON_PROGRAM,
                          "app/a.kt": "fun a() {}\n", "app/b.kt": "fun b() {}\n"})
        result = scan(self.root)
        # config.guess has a suffix (.guess): the shebang grammar is for suffix-less files only
        self.assertEqual({(record["path"], record["language"]) for record in result.files},
                         {("src/hello.c", "c"), ("fetch", "bash")})
        self.assertIn(("bash", SHELL.encode()), FakeParser.parsed)
        no_grammar = [gap for gap in result.gaps if gap["kind"] == "no-grammar"]
        self.assertEqual(no_grammar, [
            {"kind": "no-grammar", "path": None, "detail": "1 file(s) with suffix .guess"},
            {"kind": "no-grammar", "path": None, "detail": "2 file(s) with suffix .kt"},
            {"kind": "no-grammar", "path": None, "detail": "1 file(s) with suffix .patch"},
            {"kind": "no-grammar", "path": None, "detail": "1 file(s) with suffix .png"},
            {"kind": "no-grammar", "path": "app/a.kt", "detail": "no grammar for suffix .kt"},
            {"kind": "no-grammar", "path": "app/b.kt", "detail": "no grammar for suffix .kt"},
            {"kind": "no-grammar", "path": "config.guess", "detail": "no grammar for suffix .guess"},
            {"kind": "no-grammar", "path": "fix-build.patch", "detail": "no grammar for suffix .patch"},
            {"kind": "no-grammar", "path": "logo.png", "detail": "no grammar for suffix .png"}])
        self.assertEqual(result.totals["non_source"], 1)   # README

    def test_path_list_is_bounded_with_an_overflow_count(self):
        write(self.root, {f"m/{n}.kt": "x\n" for n in range(4)})
        with patch.object(treesitter_ast, "NO_GRAMMAR_PATHS", 3):
            result = scan(self.root)
        listed = [gap for gap in result.gaps if gap["kind"] == "no-grammar" and gap["path"]]
        self.assertEqual(len(listed), 3)
        self.assertIn({"kind": "no-grammar", "path": None, "detail": "1 more file(s) without a grammar are not listed "
                       "by path (cap 3)"}, result.gaps)

    def test_suffixless_file_without_a_known_shebang_keeps_no_grammar(self):
        write(self.root, {"tool": "#!/usr/bin/perl\nprint 1;\n", "Makefile": "#!/bin/sh\n"})
        result = scan(self.root)
        self.assertEqual(result.files, [])
        self.assertIn({"kind": "no-grammar", "path": "tool", "detail": "no grammar for suffix (none)"}, result.gaps)
        self.assertEqual(result.totals["non_source"], 1)

    def test_job_applicability_sees_shebang_scripts(self):
        import treesitter_ast_job
        write(self.root, {"bin/deploy": SHELL, "README": "x\n"})
        self.assertEqual(treesitter_ast_job.applicable_languages(self.root), ["bash"])


class CandidateSearchWithCensus(unittest.TestCase):
    """Acceptance: what the census changes in 04-owasp-candidate-search and so in the universe decision."""

    def setUp(self):
        self.temporary = tempfile.TemporaryDirectory()
        self.addCleanup(self.temporary.cleanup)
        self.base = Path(self.temporary.name)

    def target(self, extra: dict[str, bytes | str]):
        """(snapshot root, code index as 02-code-index holds it, tree-sitter gaps) for HELLO plus ``extra``."""
        root = self.base / f"src-{len(list(self.base.iterdir()))}"
        tree = guard.Tree(root, guard.HELLO)
        write(root, extra)
        connection = tree.index()
        result = scan(root)
        for record in result.files:
            if record["language"] != "c":   # shebang scripts: tree-sitter rows, language keyed by suffix (None)
                connection.execute("INSERT INTO files VALUES(?,?,NULL,'treesitter')", (record["path"], HEX))
        return root, connection, result.gaps

    def search(self, connection, gaps, language_census=None):
        result = search_mod.search(connection, RULES, sast_hits=[], treesitter_gaps=gaps, language_census=language_census)
        self.assertEqual(validate_document(search_document(result), "owasp-candidate-search.schema.json"), [])
        return result

    @staticmethod
    def chapter(result, chapter_id):
        return next(row for row in result["chapters"] if row["chapter_id"] == chapter_id)

    def test_non_program_files_do_not_make_chapters_gaps_with_a_census(self):
        root, connection, gaps = self.target(NON_PROGRAM)
        result = self.search(connection, gaps, census(root))
        self.assertTrue(result["coverage"]["complete"])
        self.assertEqual(result["coverage"]["unsearched_languages"], [])
        v3 = self.chapter(result, "V3")
        self.assertEqual((v3["coverage_complete"], v3["candidate_count"]), (True, 0))
        decision = universe_mod._decide("V3", v3, [], [], [], True)
        self.assertEqual(decision[:2], ("not_applicable", "no_candidates_complete_coverage"))
        classes = {row["class"]: row["paths"] for row in result["coverage"]["file_classes"]}
        self.assertEqual(classes, {"binary_media": ["logo.png"], "patch_diff": ["fix-build.patch"],
                                   "build_system": ["config.guess"], "documentation": ["README"],
                                   "vendored": ["vendor/cjson/cJSON.c"]})
        self.assertNotIn("language_census_absent", {gap["kind"] for gap in result["gaps"]})
        facility = next(row for row in result["coverage"]["facilities"] if row["facility"] == "language_census")
        self.assertEqual(facility["status"], "used")

    def test_without_a_census_coverage_is_strict_and_the_absence_is_a_gap(self):
        root, connection, gaps = self.target(NON_PROGRAM)
        result = self.search(connection, gaps)
        self.assertFalse(result["coverage"]["complete"])
        self.assertNotIn("file_classes", result["coverage"])
        self.assertEqual([row["coverage_complete"] for row in result["chapters"]], [False] * 17)
        self.assertEqual(universe_mod._decide("V3", self.chapter(result, "V3"), [], [], [], True)[0], "gap")
        absent = [gap for gap in result["gaps"] if gap["kind"] == "language_census_absent"]
        self.assertEqual(absent[0]["chapter_ids"], [f"V{n}" for n in range(1, 18)])
        # no-grammar files are counted by path (not twice) and config.guess, now parsed, is excluded
        self.assertEqual(result["coverage"]["unsearched_languages"],
                         [{"language": "unknown.patch", "file_count": 1, "reason": "no_grammar"},
                          {"language": "unknown.png", "file_count": 1, "reason": "no_grammar"}])

    def test_without_a_census_listed_no_grammar_paths_honour_exclusion_globs(self):
        gaps = [{"kind": "no-grammar", "path": None, "detail": "2 file(s) with suffix .kt"},
                {"kind": "no-grammar", "path": "app/A.kt", "detail": "no grammar for suffix .kt"},
                {"kind": "no-grammar", "path": "tests/ATest.kt", "detail": "no grammar for suffix .kt"},
                {"kind": "no-grammar", "path": None, "detail": "4 more file(s) without a grammar are not listed by path (cap 2)"}]
        result = self.search(guard.Tree(self.base / "t", guard.HELLO).index(), gaps)
        self.assertEqual(result["coverage"]["unsearched_languages"],
                         [{"language": "kotlin", "file_count": 1, "reason": "no_grammar"},
                          {"language": "unknown", "file_count": 4, "reason": "no_grammar"}])

    def test_an_unparsed_kotlin_file_makes_coverage_incomplete(self):
        root, connection, gaps = self.target({**NON_PROGRAM, "app/Main.kt": "fun main() {}\n"})
        result = self.search(connection, gaps, census(root))
        self.assertFalse(result["coverage"]["complete"])
        self.assertEqual(result["coverage"]["unsearched_languages"],
                         [{"language": "kotlin", "file_count": 1, "reason": "no_grammar"}])
        self.assertFalse(self.chapter(result, "V3")["coverage_complete"])
        self.assertEqual(universe_mod._decide("V3", self.chapter(result, "V3"), [], [], [], True)[1], "coverage_incomplete")

    def test_excluded_program_files_and_unknown_text_do_not_reduce_completeness(self):
        root, connection, gaps = self.target({"tests/ATest.kt": "class ATest\n", "notes": "plain text\n",
                                              "tool": "#!/usr/bin/tclsh\nputs x\n"})
        result = self.search(connection, gaps, census(root))
        self.assertEqual(result["coverage"]["unsearched_languages"],
                         [{"language": "tclsh", "file_count": 1, "reason": "no_grammar"}])   # a shebang script still counts
        unknown = [gap for gap in result["gaps"] if gap["kind"] == "unclassified_text"]
        self.assertIn("notes", unknown[0]["statement"])
        unknown_text = next(row for row in result["coverage"]["file_classes"] if row["class"] == "unknown_text")
        self.assertEqual((unknown_text["file_count"], unknown_text["paths"]), (1, ["notes"]))
        root, connection, gaps = self.target({"tests/ATest.kt": "class ATest\n", "notes": "plain text\n"})
        self.assertTrue(self.search(connection, gaps, census(root))["coverage"]["complete"])

    def test_suffixless_shell_script_is_searched_as_bash(self):
        root, connection, gaps = self.target({"fetch": SHELL})
        connection.execute("INSERT INTO ts_functions VALUES('fetch','fetch','function_definition',2,4,'bash')")
        connection.execute("INSERT INTO ts_calls VALUES('fetch',3,'curl')")
        connection.execute("INSERT INTO ts_calls VALUES('fetch',5,'eval')")
        result = self.search(connection, gaps, census(root))
        self.assertTrue(result["coverage"]["complete"])
        self.assertEqual(result["coverage"]["searched_languages"], ["bash", "c"])
        v12 = {(row["file"], row["symbol"]): row for row in result["candidates"] if row["chapter_id"] == "V12"}
        self.assertEqual(v12[("fetch", "fetch")]["language"], "bash")
        self.assertIn(("fetch", "<module>"), {(row["file"], row["symbol"]) for row in result["candidates"]
                                               if row["chapter_id"] == "V1"})
        strict = self.search(connection, gaps)
        self.assertIn({"language": "unknown", "file_count": 1, "reason": "no_rules_for_language"},
                      strict["coverage"]["unsearched_languages"])

    def test_census_rows_it_could_not_list_keep_coverage_incomplete(self):
        root, connection, gaps = self.target(NON_PROGRAM)
        bounded = census(root, max_rows=2)
        result = self.search(connection, gaps, bounded)
        self.assertFalse(result["coverage"]["complete"])
        self.assertEqual(result["coverage"]["unsearched_languages"],
                         [{"language": "unclassified", "file_count": bounded["totals"]["unlisted"], "reason": "not_indexed"}])

    def test_cli_takes_the_census(self):
        import sqlite3
        root, connection, gaps = self.target(NON_PROGRAM)
        database, census_path, ts_path = self.base / "index.sqlite", self.base / "census.json", self.base / "ts.json"
        target = sqlite3.connect(database); connection.backup(target); target.close()
        census_path.write_text(json.dumps(census(root))); ts_path.write_text(json.dumps(gaps))
        out = self.base / "out.json"
        self.assertEqual(search_mod.main(["--index", str(database), "--treesitter-ast", str(ts_path), "--language-census",
                                          str(census_path), "--output", str(out)]), 0)
        self.assertIn("file_classes", json.loads(out.read_text())["coverage"])


class Job(unittest.TestCase):
    def setUp(self):
        self.temporary = tempfile.TemporaryDirectory()
        self.addCleanup(self.temporary.cleanup)
        self.old_runs = state.RUNS
        state.RUNS = Path(self.temporary.name) / "runs"
        self.addCleanup(setattr, state, "RUNS", self.old_runs)
        self.target = write(Path(self.temporary.name) / "target", {"src/hello.c": "int main(void) { return 0; }\n",
                                                                    **NON_PROGRAM})
        atomic_json(state.RUNS / RUN_ID / "inputs" / "artifact-manifest.json", {"target": {"repo_path": str(self.target)}})

    def test_run_publishes_a_schema_valid_census_and_validate_rederives_it(self):
        result = census_mod.run(RUN_ID, "dagster-test")
        attempt = census_mod.root(RUN_ID) / "attempts" / result["attempt_id"]
        published = census_mod.load(attempt)
        self.assertEqual(published["job_id"], census_mod.JOB)
        self.assertEqual({row["path"]: row["class"] for row in published["files"]},
                         {"src/hello.c": "program:c", "logo.png": "binary_media", "fix-build.patch": "patch_diff",
                          "config.guess": "build_system", "README": "documentation"})
        self.assertEqual(census_mod.validate(RUN_ID), attempt)
        (self.target / "new.kt").write_text("fun x() {}\n")
        with self.assertRaises(state.Blocked):
            census_mod.validate(RUN_ID)


if __name__ == "__main__":
    unittest.main()
