"""Generate the SEI CERT rule-pack coverage report.

``rules/sei-cert/COVERAGE.md`` is a generated view of the mapping files and fixtures. It is
regenerated with ``python -m appsec_review.rulepacks.sei_cert report`` and never hand-edited; a test
fails when it is stale. Engine execution and multivuln results are run-owned and are rendered from
an evaluation directory with ``--evaluation`` instead of being committed.
"""

from __future__ import annotations

from collections import Counter, defaultdict
from typing import Any, Mapping

from .pack import Pack, compute_lock
from .validate import IMPLEMENTED_STATUSES, STATUSES, collect_expectations

LANGUAGE_NAMES = {"c": "SEI CERT C", "cpp": "SEI CERT C++", "java": "SEI CERT Oracle Java",
                  "android": "SEI CERT Android (work in progress)"}
DELEGATED = ("REQUIRES_DATAFLOW", "REQUIRES_COMPILER_OR_IR", "REQUIRES_CODEQL", "REQUIRES_MANUAL_REVIEW")
UNSUPPORTED = ("UNSUPPORTED_SEMANTIC", "UNSUPPORTED_LANGUAGE", "DUPLICATE_EXISTING_RULE")


def _table(header: list[str], rows: list[list[Any]]) -> list[str]:
    lines = ["| " + " | ".join(header) + " |", "| " + " | ".join("---" for _ in header) + " |"]
    lines += ["| " + " | ".join(str(cell) for cell in row) + " |" for row in rows]
    return lines


def render(pack: Pack, evaluation: Mapping[str, Any] | None = None) -> str:
    lock = compute_lock(pack.root)
    entries = sorted(pack.entries.values(), key=lambda item: (item["language"], item["key"]))
    expectations = collect_expectations(pack)
    kinds_by_rule: dict[str, Counter[str]] = defaultdict(Counter)
    for item in expectations:
        kinds_by_rule[item.rule_id][item.kind.split(":")[0]] += 1
    out = [
        "# SEI CERT rule-pack coverage",
        "",
        "<!-- Generated by `python -m appsec_review.rulepacks.sei_cert report`; do not edit. -->",
        "",
        f"Pack `{pack.manifest['id']}` {pack.manifest['version']}, rule tree "
        f"`{lock['rule_files_sha256'][:16]}`, official source revision "
        f"`{pack.index['source_revision'][:12]}` retrieved {pack.index['retrieved']}.",
        "",
        "## How to read this report",
        "",
        "Five different things are easy to conflate. Only the first two are recorded here:",
        "",
        "1. **Rule-pack implementation coverage**: which CERT rules have engine rules, and whether those",
        "   rules cover the rule's whole syntactic condition (`SUPPORTED`) or a named subset (`PARTIAL`).",
        "2. **Test-fixture coverage**: which positive, variant, negative, near-miss, and exception cases",
        "   each engine rule is tested against.",
        "3. **Analyzer execution success**: whether Semgrep and OpenGrep ran the pack without errors,",
        "   skipped files, or truncation on a given target. This is run-owned evidence.",
        "4. **Findings on multivuln**: what the pack reports on the pinned corpus. Run-owned evidence.",
        "5. **CERT compliance** of a target, which none of the above establishes. `SUPPORTED` means the",
        "   pack detects every syntactic form of the rule's condition within the pack-wide limits; it does",
        "   not make a target conformant, and a rule with no findings is not a passed rule.",
        "",
        "Rules with a `REQUIRES_*` or `UNSUPPORTED_*` status produce no rule-pack findings at all. Their",
        "absence of findings is a named coverage gap, never evidence that a target is clean.",
        "",
        "## Totals",
        "",
    ]
    counts = Counter(entry["status"] for entry in entries)
    out += _table(["Status", "CERT rules"], [[status, counts.get(status, 0)] for status in STATUSES] +
                  [["**Total inventoried**", len(entries)]])
    out += ["", "## By CERT language", ""]
    rows = []
    for language in LANGUAGE_NAMES:
        subset = [entry for entry in entries if entry["language"] == language]
        c = Counter(entry["status"] for entry in subset)
        rows.append([LANGUAGE_NAMES[language], len(subset), c["SUPPORTED"], c["PARTIAL"],
                     sum(c[s] for s in UNSUPPORTED), c["REQUIRES_CODEQL"], c["REQUIRES_COMPILER_OR_IR"],
                     c["REQUIRES_DATAFLOW"], c["REQUIRES_MANUAL_REVIEW"]])
    out += _table(["Standard", "Rules", "Supported", "Partial", "Unsupported", "CodeQL", "Compiler/IR",
                   "Data flow", "Manual review"], rows)
    out += ["", "## By CERT category", ""]
    rows = []
    categories: dict[tuple[str, str], Counter[str]] = defaultdict(Counter)
    for entry in entries:
        categories[(entry["language"], entry["category"])][entry["status"]] += 1
    for (language, category), c in sorted(categories.items()):
        rows.append([language, category, sum(c.values()), c["SUPPORTED"], c["PARTIAL"],
                     sum(c[s] for s in UNSUPPORTED), sum(c[s] for s in DELEGATED)])
    out += _table(["Standard", "Category", "Rules", "Supported", "Partial", "Unsupported", "Delegated"], rows)
    out += ["", "## Implemented CERT rules", ""]
    rows = []
    for entry in entries:
        if entry["status"] not in IMPLEMENTED_STATUSES:
            continue
        rule_ids = entry["implementation"]["semgrep_rule_ids"]
        cases = Counter()
        for rule_id in rule_ids:
            cases.update(kinds_by_rule[rule_id])
        case_text = ", ".join(f"{kind} {count}" for kind, count in sorted(cases.items()))
        rows.append([f"[{entry['id']}]({entry['source']['url']})", entry["status"], entry["confidence"],
                     len(rule_ids), case_text, entry["implementation"]["coverage_note"]])
    out += _table(["CERT rule", "Status", "Confidence", "Engine rules", "Fixture cases", "Covered subset"], rows)
    out += ["", "## Delegated and unsupported CERT rules", "",
            "Each rule below needs the named analysis class; the mapping files list recommended analyzers and,",
            "for C++, the vendored CodeQL CERT queries under `rules/cpp-cert/codeql/`.", ""]
    for status in DELEGATED + UNSUPPORTED:
        ids = [entry["key"] for entry in entries if entry["status"] == status]
        if ids:
            out += [f"- **{status}** ({len(ids)}): " + ", ".join(ids)]
    candidates = [entry["key"] for entry in entries if entry.get("pattern_candidate")]
    out += ["", f"Unimplemented rules whose condition looks syntactic and may become future pack rules "
            f"({len(candidates)}): " + ", ".join(candidates) + "."]
    out += ["", "## Pack-wide limitations", ""]
    out += [f"- {item}" for item in pack.manifest["global_limitations"]]
    if evaluation is not None:
        out += _render_evaluation(evaluation)
    return "\n".join(out) + "\n"


def _render_evaluation(evaluation: Mapping[str, Any]) -> list[str]:
    out = ["", "## Evaluation run", "",
           f"Status **{evaluation['status']}** for pack tree `{evaluation['pack']['tree_sha256'][:16]}`.", ""]
    out += _table(["Engine", "Version", "Executed cleanly"],
                  [[engine, data["version"], data["succeeded"]] for engine, data in evaluation["engines"].items()])
    out += ["", "### Per-rule fixture results", ""]
    rows = []
    for rule_id, result in sorted(evaluation["rules"].items()):
        cells = [rule_id.removeprefix("appsec-review.sei-cert.")]
        for engine in ("semgrep", "opengrep"):
            m = result["engines"][engine]["metrics"]
            cells.append(f"TP {m['true_positives']} / FP {m['false_positives']} / FN {m['false_negatives']} / "
                         f"known FN {m['known_false_negatives']} / known FP {m['known_false_positives']} / "
                         f"excluded {m['expected_exclusions']}")
        rows.append(cells)
    out += _table(["Rule", "Semgrep", "OpenGrep"], rows)
    differential = evaluation["differential"]
    out += ["", f"Fixture differential: engines {'agree' if differential['agree'] else 'DISAGREE'}."]
    multivuln = evaluation["multivuln"]
    out += ["", "### Multivuln", ""]
    if multivuln["status"] == "NOT_RUN":
        out += [f"Not run: {multivuln['gap']}"]
    else:
        out += [f"Status **{multivuln['status']}** at `{multivuln['commit']}` over {len(multivuln['scanned_files'])} files; "
                f"engines {'agree' if multivuln['differential']['agree'] else 'DISAGREE'}.", ""]
        out += _table(["CERT rule", "Findings"], [[cert, count] for cert, count in multivuln["findings_by_cert"].items()])
        out += ["", "Known false negatives on the corpus (delegated):", ""]
        out += [f"- {item['cert']} at `{item['path']}:{item['line']}` -> {item['delegated_to']}: {item['note']}"
                for item in multivuln["known_false_negatives"]]
    if evaluation["failures"]:
        out += ["", "### Failures", ""] + [f"- {item}" for item in evaluation["failures"]]
    return out
