#!/usr/bin/env python3
"""Fail on schemas that copy a shared format inline instead of referencing it.

A schema node duplicates a kind of schemas/common/formats.schema.json when its ``pattern`` equals
the kind's pattern (a trailing ``$`` and ``\\Z`` count as the same anchor) or its ``enum`` is the
kind's value set. Such a node should be ``{"$ref": "common/formats.schema.json#/$defs/<kind>"}``.

The copies that predate the shared module are counted per (schema, kind) in
schemas/common/inline-format-baseline.json. Converting them edits top-level schemas, which changes
every job's definition hash, so it is done deliberately, not by this lint. The lint fails when:

* a schema has more inline copies of a kind than its baseline allows (a new copy), or
* a schema has fewer than its baseline (a converted copy): regenerate the baseline with
  ``python3 schema_format_lint.py --write-baseline`` so the ratchet only tightens.
"""
from __future__ import annotations

import json
import sys
from collections import Counter
from pathlib import Path
from typing import Any

from formats import FORMATS_SCHEMA
from schema_keyword_lint import nodes, schema_files
from schema_validate import SCHEMAS_DIR

BASELINE = "common/inline-format-baseline.json"


def _anchor(pattern: str) -> str:
    for end in ("\\Z", "$"):
        if pattern.endswith(end) and not pattern.endswith("\\" + end):
            return pattern[: -len(end)]
    return pattern


def _enum_key(values: list) -> tuple:
    return tuple(sorted(json.dumps(v, sort_keys=True) for v in values))


def signatures(schemas_dir: Path = SCHEMAS_DIR) -> dict[tuple[str, Any], str]:
    """{("pattern", normalized) | ("enum", value set): kind} for the shared kinds."""
    defs = json.loads((schemas_dir / FORMATS_SCHEMA).read_text(encoding="utf-8"))["$defs"]
    table: dict[tuple[str, Any], str] = {}
    for kind, node in sorted(defs.items()):
        if "pattern" in node:
            table.setdefault(("pattern", _anchor(node["pattern"])), kind)
        if "enum" in node:
            table.setdefault(("enum", _enum_key(node["enum"])), kind)
    return table


def inline_copies(schemas_dir: Path = SCHEMAS_DIR) -> dict[str, dict[str, int]]:
    """{schema: {kind: number of inline copies}} over every schema except the formats file."""
    table = signatures(schemas_dir)
    found: dict[str, Counter] = {}
    for name, path in schema_files(schemas_dir):
        if name == FORMATS_SCHEMA:
            continue
        document = json.loads(path.read_text(encoding="utf-8"))
        for _, node in nodes(document):
            hits = []
            if isinstance(node.get("pattern"), str):
                hits.append(table.get(("pattern", _anchor(node["pattern"]))))
            if isinstance(node.get("enum"), list):
                hits.append(table.get(("enum", _enum_key(node["enum"]))))
            for kind in filter(None, hits):
                found.setdefault(name, Counter())[kind] += 1
    return {name: dict(sorted(counts.items())) for name, counts in sorted(found.items())}


def load_baseline(schemas_dir: Path = SCHEMAS_DIR) -> dict[str, dict[str, int]]:
    path = schemas_dir / BASELINE
    return json.loads(path.read_text(encoding="utf-8"))["copies"] if path.exists() else {}


def render_baseline(copies: dict[str, dict[str, int]]) -> str:
    return json.dumps({
        "description": "Inline copies of shared formats that predate schemas/common/formats.schema.json, "
                       "per schema and kind. Generated by appsec-review-process/schema_format_lint.py "
                       "--write-baseline; the count may only go down.",
        "copies": copies}, indent=2, sort_keys=True) + "\n"


def problems(schemas_dir: Path = SCHEMAS_DIR) -> list[str]:
    current, baseline = inline_copies(schemas_dir), load_baseline(schemas_dir)
    out = []
    for name in sorted(set(current) | set(baseline)):
        now, allowed = current.get(name, {}), baseline.get(name, {})
        for kind in sorted(set(now) | set(allowed)):
            have, may = now.get(kind, 0), allowed.get(kind, 0)
            if have > may:
                out.append(f"{name}: {have - may} new inline copy(ies) of {kind}; use "
                           f'{{"$ref": "{FORMATS_SCHEMA}#/$defs/{kind}"}}')
            elif have < may:
                out.append(f"{name}: baseline allows {may} inline {kind}, found {have}; "
                           "run schema_format_lint.py --write-baseline")
    return out


def main(argv: list[str]) -> int:
    if argv == ["--write-baseline"]:
        (SCHEMAS_DIR / BASELINE).write_text(render_baseline(inline_copies()), encoding="utf-8")
        return 0
    found = problems()
    for line in found:
        print(line)
    total = sum(sum(k.values()) for k in inline_copies().values())
    print(f"{total} grandfathered inline copies; {len(found)} problem(s)")
    return 1 if found else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
